org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
SUPABASE_URL=https://mwzjrfyqjhvudmvzuuxu.supabase.co
SUPABASE_PUBLISHABLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13empyZnlxamh2dWRtdnp1dXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTk3NDYsImV4cCI6MjA3Mjk5NTc0Nn0.m_ziUZJwUMKjwR1pffP7X_tVKeA589g2C2mPzcf1r78
